SystemOrganization addCategory: #'IoT-Core'!
SystemOrganization addCategory: 'IoT-Core-ConditionModel'!
SystemOrganization addCategory: 'IoT-Core-IndentifierProviderModel'!
SystemOrganization addCategory: 'IoT-Core-ObjectBindingModel'!
SystemOrganization addCategory: 'IoT-Core-PeriodicalSchedulerModel'!
SystemOrganization addCategory: 'IoT-Core-PriorityQueueModel'!
SystemOrganization addCategory: 'IoT-Core-SystemModel'!
SystemOrganization addCategory: 'IoT-Core-TimeSystemModel'!
