SystemOrganization addCategory: #'IoT-Core'!
SystemOrganization addCategory: 'IoT-Core-Common'!
SystemOrganization addCategory: 'IoT-Core-Feed'!
SystemOrganization addCategory: 'IoT-Core-FeedSystem'!
SystemOrganization addCategory: 'IoT-Core-IoTSystem'!
SystemOrganization addCategory: 'IoT-Core-TimeSystem'!
SystemOrganization addCategory: 'IoT-Core-Trigger'!
SystemOrganization addCategory: 'IoT-Core-TriggerSystem'!
