actions
preload: aLoader package: aPackageSpec

	Smalltalk
		at: #SystemInterface
		put: nil.

	Smalltalk
		at: #TimeSystemInterface
		put: nil.
		
	Smalltalk
		at: #EventNotificationSystemInterface
		put: nil.
		 
	Smalltalk
		at: #CommandManagementSystemInterface
		put: nil.
	
	Smalltalk
		at: #DataManagementSystemInterface
		put: nil.
		
	Smalltalk
		at: #ConditionalTriggersSystemInterface
		put: nil.
		
	