SystemOrganization addCategory: #'IoT-Tests'!
SystemOrganization addCategory: 'IoT-Tests-Condition'!
SystemOrganization addCategory: 'IoT-Tests-ConditionalTrigger'!
SystemOrganization addCategory: 'IoT-Tests-ConditionalTriggersSystem'!
SystemOrganization addCategory: 'IoT-Tests-Feed'!
SystemOrganization addCategory: 'IoT-Tests-FeedsSystem'!
SystemOrganization addCategory: 'IoT-Tests-PeriodicalScheduler'!
